import 'package:flutter/material.dart';
import 'package:tw_mobile/data/classes/team.dart';

List<Team> mlsTeams = [
  Team(
    teamId: 66,
    teamName: 'Atlanta United FC',
    arenaName: 'Mercedes-Benz Stadium',
    arenaLocation: 'Atlanta, Georgia',
    state: 'Georgia',
    logoPath: 'lib/assets/leagues/mls/atlanta.svg',
    abbName: 'ATL',
    leagueId: 5,
    color: const Color(0xFFA6192E),
  ),
  Team(
    teamId: 67,
    teamName: 'Austin FC',
    arenaName: 'Q2 Stadium',
    arenaLocation: 'Austin, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/mls/austin.svg',
    abbName: 'AFC',
    leagueId: 5,
    color: const Color(0xFF00B140),
  ),
  Team(
    teamId: 78,
    teamName: 'CF Montréal',
    arenaName: 'Stade Saputo',
    arenaLocation: 'Montreal, Quebec',
    state: 'Quebec',
    logoPath: 'lib/assets/leagues/mls/montreal.svg',
    abbName: 'MTL',
    leagueId: 5,
    color: const Color(0xFF12264C),
  ),
  Team(
    teamId: 152,
    teamName: 'Charlotte FC',
    arenaName: 'Bank of America Stadium',
    arenaLocation: 'Charlotte, North Carolina',
    state: 'North Carolina',
    logoPath: 'lib/assets/leagues/mls/charlotte.svg',
    abbName: 'CLT',
    leagueId: 5,
    color: const Color(0xFF00529B),
  ),
  Team(
    teamId: 68,
    teamName: 'Chicago Fire FC',
    arenaName: 'Soldier Field',
    arenaLocation: 'Chicago, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/mls/chicago.svg',
    abbName: 'CHI',
    leagueId: 5,
    color: const Color(0xFFAF1E2D),
  ),
  Team(
    teamId: 70,
    teamName: 'Colorado Rapids',
    arenaName: 'DICK\'S Sporting Goods Park',
    arenaLocation: 'Commerce City, Colorado',
    state: 'Colorado',
    logoPath: 'lib/assets/leagues/mls/colorado.svg',
    abbName: 'COL',
    leagueId: 5,
    color: const Color(0xFF910025),
  ),
  Team(
    teamId: 71,
    teamName: 'Columbus Crew SC',
    arenaName: 'Lower.com Field',
    arenaLocation: 'Columbus, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/mls/columbus.svg',
    abbName: 'CLB',
    leagueId: 5,
    color: const Color(0xFF231F20),
  ),
  Team(
    teamId: 72,
    teamName: 'D.C. United',
    arenaName: 'Audi Field',
    arenaLocation: 'Washington, D.C.',
    state: 'Washington, D.C.',
    logoPath: 'lib/assets/leagues/mls/dcunited.svg',
    abbName: 'DC',
    leagueId: 5,
    color: const Color(0xFF000000),
  ),
  Team(
    teamId: 69,
    teamName: 'FC Cincinnati',
    arenaName: 'TQL Stadium',
    arenaLocation: 'Cincinnati, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/mls/cincinnati.svg',
    abbName: 'CIN',
    leagueId: 5,
    color: const Color(0xFFFC4C02),
  ),
  Team(
    teamId: 73,
    teamName: 'FC Dallas',
    arenaName: 'Toyota Stadium',
    arenaLocation: 'Frisco, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/mls/dallas.svg',
    abbName: 'DAL',
    leagueId: 5,
    color: const Color(0xFFD71920),
  ),
  Team(
    teamId: 74,
    teamName: 'Houston Dynamo FC',
    arenaName: 'BBVA Stadium',
    arenaLocation: 'Houston, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/mls/houston.svg',
    abbName: 'HOU',
    leagueId: 5,
    color: const Color(0xFFFFD200),
  ),
  Team(
    teamId: 11,
    teamName: 'Inter Miami CF',
    arenaName: 'DRV PNK Stadium',
    arenaLocation: 'Fort Lauderdale, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/mls/miami.svg',
    abbName: 'MIA',
    leagueId: 5,
    color: const Color(0xFF000000),
  ),
  Team(
    teamId: 76,
    teamName: 'Los Angeles FC',
    arenaName: 'Banc of California Stadium',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/mls/lafc.svg',
    abbName: 'LAFC',
    leagueId: 5,
    color: const Color(0xFF000000),
  ),
  Team(
    teamId: 75,
    teamName: 'Los Angeles Galaxy',
    arenaName: 'Dignity Health Sports Park',
    arenaLocation: 'Carson, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/mls/lagalaxy.svg',
    abbName: 'LA',
    leagueId: 5,
    color: const Color(0xFF00245D),
  ),
  Team(
    teamId: 77,
    teamName: 'Minnesota United FC',
    arenaName: 'Allianz Field',
    arenaLocation: 'Saint Paul, Minnesota',
    state: 'Minnesota',
    logoPath: 'lib/assets/leagues/mls/minnesota.svg',
    abbName: 'MIN',
    leagueId: 5,
    color: const Color(0xFF9DBB22),
  ),
  Team(
    teamId: 151,
    teamName: 'Nashville SC',
    arenaName: 'Nissan Stadium',
    arenaLocation: 'Nashville, Tennessee',
    state: 'Tennessee',
    logoPath: 'lib/assets/leagues/mls/nashville.svg',
    abbName: 'NSH',
    leagueId: 5,
    color: const Color(0xFF002E5D),
  ),
  Team(
    teamId: 13,
    teamName: 'New England Revolution',
    arenaName: 'Gillette Stadium',
    arenaLocation: 'Foxborough, Massachusetts',
    state: 'Massachusetts',
    logoPath: 'lib/assets/leagues/mls/newengland.svg',
    abbName: 'NE',
    leagueId: 5,
    color: const Color(0xFF002B5C),
  ),
  Team(
    teamId: 79,
    teamName: 'New York City FC',
    arenaName: 'Yankee Stadium',
    arenaLocation: 'New York, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/mls/nycfc.svg',
    abbName: 'NYCFC',
    leagueId: 5,
    color: const Color(0xFF6CACE4),
  ),
  Team(
    teamId: 80,
    teamName: 'New York Red Bulls',
    arenaName: 'Red Bull Arena',
    arenaLocation: 'Harrison, New Jersey',
    state: 'New Jersey',
    logoPath: 'lib/assets/leagues/mls/nyredbulls.svg',
    abbName: 'NYRB',
    leagueId: 5,
    color: const Color(0xFFED1E79),
  ),
  Team(
    teamId: 81,
    teamName: 'Orlando City SC',
    arenaName: 'Exploria Stadium',
    arenaLocation: 'Orlando, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/mls/orlando.svg',
    abbName: 'ORL',
    leagueId: 5,
    color: const Color(0xFF633492),
  ),
  Team(
    teamId: 82,
    teamName: 'Philadelphia Union',
    arenaName: 'Subaru Park',
    arenaLocation: 'Chester, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/mls/philadelphia.svg',
    abbName: 'PHI',
    leagueId: 5,
    color: const Color(0xFF002F5D),
  ),
  Team(
    teamId: 83,
    teamName: 'Portland Timbers',
    arenaName: 'Providence Park',
    arenaLocation: 'Portland, Oregon',
    state: 'Oregon',
    logoPath: 'lib/assets/leagues/mls/portland.svg',
    abbName: 'POR',
    leagueId: 5,
    color: const Color(0xFF004812),
  ),
  Team(
    teamId: 84,
    teamName: 'Real Salt Lake',
    arenaName: 'Rio Tinto Stadium',
    arenaLocation: 'Sandy, Utah',
    state: 'Utah',
    logoPath: 'lib/assets/leagues/mls/rsl.svg',
    abbName: 'RSL',
    leagueId: 5,
    color: const Color(0xFFB30838),
  ),
  Team(
    teamId: 85,
    teamName: 'San Jose Earthquakes',
    arenaName: 'PayPal Park',
    arenaLocation: 'San Jose, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/mls/sanjose.svg',
    abbName: 'SJ',
    leagueId: 5,
    color: const Color(0xFF00685E),
  ),
  Team(
    teamId: 86,
    teamName: 'Seattle Sounders FC',
    arenaName: 'Lumen Field',
    arenaLocation: 'Seattle, Washington',
    state: 'Washington',
    logoPath: 'lib/assets/leagues/mls/seattle.svg',
    abbName: 'SEA',
    leagueId: 5,
    color: const Color(0xFF005C6D),
  ),
  Team(
    teamId: 87,
    teamName: 'Sporting Kansas City',
    arenaName: 'Children\'s Mercy Park',
    arenaLocation: 'Kansas City, Kansas',
    state: 'Kansas',
    logoPath: 'lib/assets/leagues/mls/kansascity.svg',
    abbName: 'SKC',
    leagueId: 5,
    color: const Color(0xFFA89D67),
  ),
  Team(
    teamId: 153,
    teamName: 'St. Louis City SC',
    arenaName: 'CityPark',
    arenaLocation: 'St. Louis, Missouri',
    state: 'Missouri',
    logoPath: 'lib/assets/leagues/mls/stlouis.svg',
    abbName: 'STL',
    leagueId: 5,
    color: const Color(0xFFA71930),
  ),
  Team(
    teamId: 88,
    teamName: 'Toronto FC',
    arenaName: 'BMO Field',
    arenaLocation: 'Toronto, Ontario',
    state: 'Ontario',
    logoPath: 'lib/assets/leagues/mls/toronto.svg',
    abbName: 'TOR',
    leagueId: 5,
    color: const Color(0xFFE31937),
  ),
  Team(
    teamId: 89,
    teamName: 'Vancouver Whitecaps FC',
    arenaName: 'BC Place',
    arenaLocation: 'Vancouver, British Columbia',
    state: 'British Columbia',
    logoPath: 'lib/assets/leagues/mls/vancouver.svg',
    abbName: 'VAN',
    leagueId: 5,
    color: const Color(0xFF00285E),
  ),
  Team(
    teamId: 67,
    teamName: 'Austin FC',
    arenaName: 'Q2 Stadium',
    arenaLocation: 'Austin, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/mls/austin.svg',
    abbName: 'AFC',
    leagueId: 5,
    color: const Color(0xFF00B140),
  ),
];
