import 'package:flutter/material.dart';
import 'package:tw_mobile/data/classes/team.dart';

List<Team> nbaTeams = [
  Team(
    teamId: 18,
    teamName: 'Atlanta Hawks',
    arenaName: 'State Farm Arena',
    arenaLocation: 'Atlanta, Georgia',
    state: 'Georgia',
    logoPath: 'lib/assets/leagues/nba/hawks.svg',
    abbName: 'ATL',
    leagueId: 1,
    color: const Color(0xFFE03A3E),
  ),
  Team(
    teamId: 3,
    teamName: 'Boston Celtics',
    arenaName: 'TD Garden',
    arenaLocation: 'Boston, Massachusetts',
    state: 'Massachusetts',
    logoPath: 'lib/assets/leagues/nba/celtics.svg',
    abbName: 'BOS',
    leagueId: 1,
    color: const Color(0xFF007A33),
  ),
  Team(
    teamId: 20,
    teamName: 'Brooklyn Nets',
    arenaName: 'Barclays Center',
    arenaLocation: 'Brooklyn, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nba/nets.svg',
    abbName: 'BKN',
    leagueId: 1,
    color: const Color(0xFF000000),
  ),
  Team(
    teamId: 21,
    teamName: 'Charlotte Hornets',
    arenaName: 'Spectrum Center',
    arenaLocation: 'Charlotte, North Carolina',
    state: 'North Carolina',
    logoPath: 'lib/assets/leagues/nba/hornets.svg',
    abbName: 'CHA',
    leagueId: 1,
    color: const Color(0xFF00788C),
  ),
  Team(
    teamId: 22,
    teamName: 'Chicago Bulls',
    arenaName: 'United Center',
    arenaLocation: 'Chicago, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/nba/bulls.svg',
    abbName: 'CHI',
    leagueId: 1,
    color: const Color(0xFFCE1141),
  ),
  Team(
    teamId: 23,
    teamName: 'Cleveland Cavaliers',
    arenaName: 'Rocket Mortgage FieldHouse',
    arenaLocation: 'Cleveland, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/nba/cavaliers.svg',
    abbName: 'CLE',
    leagueId: 1,
    color: const Color(0xFF860038),
  ),
  Team(
    teamId: 19,
    teamName: 'Dallas Mavericks',
    arenaName: 'American Airlines Center',
    arenaLocation: 'Dallas, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nba/mavericks.svg',
    abbName: 'DAL',
    leagueId: 1,
    color: const Color(0xFF00538C),
  ),
  Team(
    teamId: 6,
    teamName: 'Denver Nuggets',
    arenaName: 'Ball Arena',
    arenaLocation: 'Denver, Colorado',
    state: 'Colorado',
    logoPath: 'lib/assets/leagues/nba/nuggets.svg',
    abbName: 'DEN',
    leagueId: 1,
    color: const Color(0xFF0E2240),
  ),
  Team(
    teamId: 24,
    teamName: 'Detroit Pistons',
    arenaName: 'Little Caesars Arena',
    arenaLocation: 'Detroit, Michigan',
    state: 'Michigan',
    logoPath: 'lib/assets/leagues/nba/pistons.svg',
    abbName: 'DET',
    leagueId: 1,
    color: const Color(0xFFC8102E),
  ),
  Team(
    teamId: 12,
    teamName: 'Golden State Warriors',
    arenaName: 'Chase Center',
    arenaLocation: 'San Francisco, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nba/gswarriors.svg',
    abbName: 'GSW',
    leagueId: 1,
    color: const Color(0xFF1D428A),
  ),
  Team(
    teamId: 25,
    teamName: 'Houston Rockets',
    arenaName: 'Toyota Center',
    arenaLocation: 'Houston, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nba/rockets.svg',
    abbName: 'HOU',
    leagueId: 1,
    color: const Color(0xFFCE1141),
  ),
  Team(
    teamId: 26,
    teamName: 'Indiana Pacers',
    arenaName: 'Bankers Life Fieldhouse',
    arenaLocation: 'Indianapolis, Indiana',
    state: 'Indiana',
    logoPath: 'lib/assets/leagues/nba/pacers.svg',
    abbName: 'IND',
    leagueId: 1,
    color: const Color(0xFF002D62),
  ),
  Team(
    teamId: 27,
    teamName: 'LA Clippers',
    arenaName: 'Crypto.com Arena',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nba/clippers.svg',
    abbName: 'LAC',
    leagueId: 1,
    color: const Color(0xFFC8102E),
  ),
  Team(
    teamId: 14,
    teamName: 'Los Angeles Lakers',
    arenaName: 'Crypto.com Arena',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nba/lakers.svg',
    abbName: 'LAL',
    leagueId: 1,
    color: const Color(0xFFFFC72C),
  ),
  Team(
    teamId: 28,
    teamName: 'Memphis Grizzlies',
    arenaName: 'FedExForum',
    arenaLocation: 'Memphis, Tennessee',
    state: 'Tennessee',
    logoPath: 'lib/assets/leagues/nba/grizzlies.svg',
    abbName: 'MEM',
    leagueId: 1,
    color: const Color(0xFF5D76A9),
  ),
  Team(
    teamId: 1,
    teamName: 'Miami Heat',
    arenaName: 'FTX Arena',
    arenaLocation: 'Miami, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nba/heat.svg',
    abbName: 'MIA',
    leagueId: 1,
    color: const Color(0xFF98002E),
  ),
  Team(
    teamId: 10,
    teamName: 'Milwaukee Bucks',
    arenaName: 'Fiserv Forum',
    arenaLocation: 'Milwaukee, Wisconsin',
    state: 'Wisconsin',
    logoPath: 'lib/assets/leagues/nba/bucks.svg',
    abbName: 'MIL',
    leagueId: 1,
    color: const Color(0xFF00471B),
  ),
  Team(
    teamId: 29,
    teamName: 'Minnesota Timberwolves',
    arenaName: 'Target Center',
    arenaLocation: 'Minneapolis, Minnesota',
    state: 'Minnesota',
    logoPath: 'lib/assets/leagues/nba/timberwolves.svg',
    abbName: 'MIN',
    leagueId: 1,
    color: const Color(0xFF0C2340),
  ),
  Team(
    teamId: 30,
    teamName: 'New Orleans Pelicans',
    arenaName: 'Smoothie King Center',
    arenaLocation: 'New Orleans, Louisiana',
    state: 'Louisiana',
    logoPath: 'lib/assets/leagues/nba/pelicans.svg',
    abbName: 'NOP',
    leagueId: 1,
    color: const Color(0xFF0C2340),
  ),
  Team(
    teamId: 5,
    teamName: 'New York Knicks',
    arenaName: 'Madison Square Garden',
    arenaLocation: 'New York City, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nba/knicks.svg',
    abbName: 'NYK',
    leagueId: 1,
    color: const Color(0xFF006BB6),
  ),
  Team(
    teamId: 31,
    teamName: 'Oklahoma City Thunder',
    arenaName: 'Paycom Center',
    arenaLocation: 'Oklahoma City, Oklahoma',
    state: 'Oklahoma',
    logoPath: 'lib/assets/leagues/nba/thunder.svg',
    abbName: 'OKC',
    leagueId: 1,
    color: const Color(0xFF007AC1),
  ),
  Team(
    teamId: 32,
    teamName: 'Orlando Magic',
    arenaName: 'Amway Center',
    arenaLocation: 'Orlando, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nba/magic.svg',
    abbName: 'ORL',
    leagueId: 1,
    color: const Color(0xFF0077C0),
  ),
  Team(
    teamId: 4,
    teamName: 'Philadelphia 76ers',
    arenaName: 'Wells Fargo Center',
    arenaLocation: 'Philadelphia, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/nba/76ers.svg',
    abbName: 'PHI',
    leagueId: 1,
    color: const Color(0xFF006BB6),
  ),
  Team(
    teamId: 16,
    teamName: 'Phoenix Suns',
    arenaName: 'Footprint Center',
    arenaLocation: 'Phoenix, Arizona',
    state: 'Arizona',
    logoPath: 'lib/assets/leagues/nba/suns.svg',
    abbName: 'PHX',
    leagueId: 1,
    color: const Color(0xFFE56020),
  ),
  Team(
    teamId: 33,
    teamName: 'Portland Trail Blazers',
    arenaName: 'Moda Center',
    arenaLocation: 'Portland, Oregon',
    state: 'Oregon',
    logoPath: 'lib/assets/leagues/nba/trailblazers.svg',
    abbName: 'POR',
    leagueId: 1,
    color: const Color(0xFFE03A3E),
  ),
  Team(
    teamId: 17,
    teamName: 'Sacramento Kings',
    arenaName: 'Golden 1 Center',
    arenaLocation: 'Sacramento, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nba/kings.svg',
    abbName: 'SAC',
    leagueId: 1,
    color: const Color(0xFF5A2D81),
  ),
  Team(
    teamId: 2,
    teamName: 'San Antonio Spurs',
    arenaName: 'AT&T Center',
    arenaLocation: 'San Antonio, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nba/spurs.svg',
    abbName: 'SAS',
    leagueId: 1,
    color: const Color(0xFFC4CED4),
  ),
  Team(
    teamId: 34,
    teamName: 'Toronto Raptors',
    arenaName: 'Scotiabank Arena',
    arenaLocation: 'Toronto, Ontario',
    state: 'Ontario',
    logoPath: 'lib/assets/leagues/nba/raptors.svg',
    abbName: 'TOR',
    leagueId: 1,
    color: const Color(0xFFCE1141),
  ),
  Team(
    teamId: 35,
    teamName: 'Utah Jazz',
    arenaName: 'Vivint Arena',
    arenaLocation: 'Salt Lake City, Utah',
    state: 'Utah',
    logoPath: 'lib/assets/leagues/nba/jazz.svg',
    abbName: 'UTA',
    leagueId: 1,
    color: const Color(0xFF002B5C),
  ),
  Team(
    teamId: 15,
    teamName: 'Washington Wizards',
    arenaName: 'Capital One Arena',
    arenaLocation: 'Washington, D.C.',
    state: 'Washington, D.C.',
    logoPath: 'lib/assets/leagues/nba/wizards.svg',
    abbName: 'WAS',
    leagueId: 1,
    color: const Color(0xFF002B5C),
  ),
];
