import 'package:tw_mobile/data/classes/team.dart';
import 'package:flutter/material.dart';

List<Team> nflTeams = [
  Team(
    teamId: 37,
    teamName: 'Arizona Cardinals',
    arenaName: 'State Farm Stadium',
    arenaLocation: 'Glendale, Arizona',
    state: 'Arizona',
    logoPath: 'lib/assets/leagues/nfl/cardinals.svg',
    abbName: 'ARI',
    leagueId: 2,
    color: const Color(0xFF97233F),
  ),
  Team(
    teamId: 36,
    teamName: 'Atlanta Falcons',
    arenaName: 'Mercedes-Benz Stadium',
    arenaLocation: 'Atlanta, Georgia',
    state: 'Georgia',
    logoPath: 'lib/assets/leagues/nfl/falcons.svg',
    abbName: 'ATL',
    leagueId: 2,
    color: const Color(0xFFA71930),
  ),
  Team(
    teamId: 7,
    teamName: 'Baltimore Ravens',
    arenaName: 'M&T Bank Stadium',
    arenaLocation: 'Baltimore, Maryland',
    state: 'Maryland',
    logoPath: 'lib/assets/leagues/nfl/ravens.svg',
    abbName: 'BAL',
    leagueId: 2,
    color: const Color(0xFF241773),
  ),
  Team(
    teamId: 38,
    teamName: 'Buffalo Bills',
    arenaName: 'Highmark Stadium',
    arenaLocation: 'Orchard Park, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nfl/bills.svg',
    abbName: 'BUF',
    leagueId: 2,
    color: const Color(0xFF00338D),
  ),
  Team(
    teamId: 39,
    teamName: 'Carolina Panthers',
    arenaName: 'Bank of America Stadium',
    arenaLocation: 'Charlotte, North Carolina',
    state: 'North Carolina',
    logoPath: 'lib/assets/leagues/nfl/panthers.svg',
    abbName: 'CAR',
    leagueId: 2,
    color: const Color(0xFF0085CA),
  ),
  Team(
    teamId: 40,
    teamName: 'Chicago Bears',
    arenaName: 'Soldier Field',
    arenaLocation: 'Chicago, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/nfl/bears.svg',
    abbName: 'CHI',
    leagueId: 2,
    color: const Color(0xFF0B162A),
  ),
  Team(
    teamId: 41,
    teamName: 'Cincinnati Bengals',
    arenaName: 'Paul Brown Stadium',
    arenaLocation: 'Cincinnati, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/nfl/bengals.svg',
    abbName: 'CIN',
    leagueId: 2,
    color: const Color(0xFFFB4F14),
  ),
  Team(
    teamId: 42,
    teamName: 'Cleveland Browns',
    arenaName: 'FirstEnergy Stadium',
    arenaLocation: 'Cleveland, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/nfl/browns.svg',
    abbName: 'CLE',
    leagueId: 2,
    color: const Color(0xFFFB4F14),
  ),
  Team(
    teamId: 43,
    teamName: 'Dallas Cowboys',
    arenaName: 'AT&T Stadium',
    arenaLocation: 'Arlington, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nfl/cowboys.svg',
    abbName: 'DAL',
    leagueId: 2,
    color: const Color(0xFF041E42),
  ),
  Team(
    teamId: 44,
    teamName: 'Denver Broncos',
    arenaName: 'Empower Field at Mile High',
    arenaLocation: 'Denver, Colorado',
    state: 'Colorado',
    logoPath: 'lib/assets/leagues/nfl/broncos.svg',
    abbName: 'DEN',
    leagueId: 2,
    color: const Color(0xFFFB4F14),
  ),
  Team(
    teamId: 45,
    teamName: 'Detroit Lions',
    arenaName: 'Ford Field',
    arenaLocation: 'Detroit, Michigan',
    state: 'Michigan',
    logoPath: 'lib/assets/leagues/nfl/lions.svg',
    abbName: 'DET',
    leagueId: 2,
    color: const Color(0xFF005A8B),
  ),
  Team(
    teamId: 46,
    teamName: 'Green Bay Packers',
    arenaName: 'Lambeau Field',
    arenaLocation: 'Green Bay, Wisconsin',
    state: 'Wisconsin',
    logoPath: 'lib/assets/leagues/nfl/packers.svg',
    abbName: 'GB',
    leagueId: 2,
    color: const Color(0xFF203731),
  ),
  Team(
    teamId: 47,
    teamName: 'Houston Texans',
    arenaName: 'NRG Stadium',
    arenaLocation: 'Houston, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nfl/texans.svg',
    abbName: 'HOU',
    leagueId: 2,
    color: const Color(0xFF03202F),
  ),
  Team(
    teamId: 48,
    teamName: 'Indianapolis Colts',
    arenaName: 'Lucas Oil Stadium',
    arenaLocation: 'Indianapolis, Indiana',
    state: 'Indiana',
    logoPath: 'lib/assets/leagues/nfl/colts.svg',
    abbName: 'IND',
    leagueId: 2,
    color: const Color(0xFF002C5F),
  ),
  Team(
    teamId: 49,
    teamName: 'Jacksonville Jaguars',
    arenaName: 'TIAA Bank Field',
    arenaLocation: 'Jacksonville, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nfl/jaguars.svg',
    abbName: 'JAX',
    leagueId: 2,
    color: const Color(0xFF006778),
  ),
  Team(
    teamId: 8,
    teamName: 'Kansas City Chiefs',
    arenaName: 'Arrowhead Stadium',
    arenaLocation: 'Kansas City, Missouri',
    state: 'Missouri',
    logoPath: 'lib/assets/leagues/nfl/chiefs.svg',
    abbName: 'KC',
    leagueId: 2,
    color: const Color(0xFFE31837),
  ),
  Team(
    teamId: 50,
    teamName: 'Las Vegas Raiders',
    arenaName: 'Allegiant Stadium',
    arenaLocation: 'Paradise, Nevada',
    state: 'Nevada',
    logoPath: 'lib/assets/leagues/nfl/raiders.svg',
    abbName: 'LV',
    leagueId: 2,
    color: const Color(0xFF000000),
  ),
  Team(
    teamId: 51,
    teamName: 'Los Angeles Chargers',
    arenaName: 'SoFi Stadium',
    arenaLocation: 'Inglewood, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nfl/chargers.svg',
    abbName: 'LAC',
    leagueId: 2,
    color: const Color(0xFF002A5E),
  ),
  Team(
    teamId: 52,
    teamName: 'Los Angeles Rams',
    arenaName: 'SoFi Stadium',
    arenaLocation: 'Inglewood, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nfl/rams.svg',
    abbName: 'LAR',
    leagueId: 2,
    color: const Color(0xFF002A5E),
  ),
  Team(
    teamId: 53,
    teamName: 'Miami Dolphins',
    arenaName: 'Hard Rock Stadium',
    arenaLocation: 'Miami Gardens, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nfl/dolphins.svg',
    abbName: 'MIA',
    leagueId: 2,
    color: const Color(0xFF008E97),
  ),
  Team(
    teamId: 54,
    teamName: 'Minnesota Vikings',
    arenaName: 'U.S. Bank Stadium',
    arenaLocation: 'Minneapolis, Minnesota',
    state: 'Minnesota',
    logoPath: 'lib/assets/leagues/nfl/vikings.svg',
    abbName: 'MIN',
    leagueId: 2,
    color: const Color(0xFF4F2683),
  ),
  Team(
    teamId: 55,
    teamName: 'New England Patriots',
    arenaName: 'Gillette Stadium',
    arenaLocation: 'Foxborough, Massachusetts',
    state: 'Massachusetts',
    logoPath: 'lib/assets/leagues/nfl/patriots.svg',
    abbName: 'NE',
    leagueId: 2,
    color: const Color(0xFF0A2342),
  ),
  Team(
    teamId: 56,
    teamName: 'New Orleans Saints',
    arenaName: 'Caesars Superdome',
    arenaLocation: 'New Orleans, Louisiana',
    state: 'Louisiana',
    logoPath: 'lib/assets/leagues/nfl/saints.svg',
    abbName: 'NO',
    leagueId: 2,
    color: const Color(0xFFD3BC8D),
  ),
  Team(
    teamId: 57,
    teamName: 'New York Giants',
    arenaName: 'MetLife Stadium',
    arenaLocation: 'East Rutherford, New Jersey',
    state: 'New Jersey',
    logoPath: 'lib/assets/leagues/nfl/giants.svg',
    abbName: 'NYG',
    leagueId: 2,
    color: const Color(0xFF0B2265),
  ),
  Team(
    teamId: 58,
    teamName: 'New York Jets',
    arenaName: 'MetLife Stadium',
    arenaLocation: 'East Rutherford, New Jersey',
    state: 'New Jersey',
    logoPath: 'lib/assets/leagues/nfl/jets.svg',
    abbName: 'NYJ',
    leagueId: 2,
    color: const Color(0xFF125740),
  ),
  Team(
    teamId: 59,
    teamName: 'Philadelphia Eagles',
    arenaName: 'Lincoln Financial Field',
    arenaLocation: 'Philadelphia, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/nfl/eagles.svg',
    abbName: 'PHI',
    leagueId: 2,
    color: const Color(0xFF004C54),
  ),
  Team(
    teamId: 60,
    teamName: 'Pittsburgh Steelers',
    arenaName: 'Heinz Field',
    arenaLocation: 'Pittsburgh, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/nfl/steelers.svg',
    abbName: 'PIT',
    leagueId: 2,
    color: const Color(0xFFFFB612),
  ),
  Team(
    teamId: 61,
    teamName: 'San Francisco 49ers',
    arenaName: 'Levi\'s Stadium',
    arenaLocation: 'Santa Clara, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nfl/49ers.svg',
    abbName: 'SF',
    leagueId: 2,
    color: const Color(0xFFAA0000),
  ),
  Team(
    teamId: 62,
    teamName: 'Seattle Seahawks',
    arenaName: 'Lumen Field',
    arenaLocation: 'Seattle, Washington',
    state: 'Washington',
    logoPath: 'lib/assets/leagues/nfl/seahawks.svg',
    abbName: 'SEA',
    leagueId: 2,
    color: const Color(0xFF002244),
  ),
  Team(
    teamId: 63,
    teamName: 'Tampa Bay Buccaneers',
    arenaName: 'Raymond James Stadium',
    arenaLocation: 'Tampa, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nfl/buccaneers.svg',
    abbName: 'TB',
    leagueId: 2,
    color: const Color(0xFFD50A0A),
  ),
  Team(
    teamId: 64,
    teamName: 'Tennessee Titans',
    arenaName: 'Nissan Stadium',
    arenaLocation: 'Nashville, Tennessee',
    state: 'Tennessee',
    logoPath: 'lib/assets/leagues/nfl/titans.svg',
    abbName: 'TEN',
    leagueId: 2,
    color: const Color(0xFF0C2340),
  ),
  Team(
    teamId: 65,
    teamName: 'Washington Commanders',
    arenaName: 'FedEx Field',
    arenaLocation: 'Landover, Maryland',
    state: 'Maryland',
    logoPath: 'lib/assets/leagues/nfl/washington.svg',
    abbName: 'WAS',
    leagueId: 2,
    color: const Color(0xFF773141),
  ),
];
