import 'package:flutter/material.dart';
import 'package:tw_mobile/data/classes/team.dart';

List<Team> nhlTeams = [
  Team(
    teamId: 120,
    teamName: 'Anaheim Ducks',
    arenaName: 'Honda Center',
    arenaLocation: 'Anaheim, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nhl/ducks.svg',
    abbName: 'ANA',
    leagueId: 3,
    color: const Color(0xFFFC4C02),
  ),
  Team(
    teamId: 121,
    teamName: 'Arizona Coyotes',
    arenaName: 'Gila River Arena',
    arenaLocation: 'Glendale, Arizona',
    state: 'Arizona',
    logoPath: 'lib/assets/leagues/nhl/coyotes.svg',
    abbName: 'ARI',
    leagueId: 3,
    color: const Color(0xFF8C2633),
  ),
  Team(
    teamId: 9,
    teamName: 'Boston Bruins',
    arenaName: 'TD Garden',
    arenaLocation: 'Boston, Massachusetts',
    state: 'Massachusetts',
    logoPath: 'lib/assets/leagues/nhl/bruins.svg',
    abbName: 'BOS',
    leagueId: 3,
    color: const Color(0xFFFFB81C),
  ),
  Team(
    teamId: 122,
    teamName: 'Buffalo Sabres',
    arenaName: 'KeyBank Center',
    arenaLocation: 'Buffalo, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nhl/sabres.svg',
    abbName: 'BUF',
    leagueId: 3,
    color: const Color(0xFF002654),
  ),
  Team(
    teamId: 123,
    teamName: 'Calgary Flames',
    arenaName: 'Scotiabank Saddledome',
    arenaLocation: 'Calgary, Alberta',
    state: 'Alberta',
    logoPath: 'lib/assets/leagues/nhl/flames.svg',
    abbName: 'CGY',
    leagueId: 3,
    color: const Color(0xFFC8102E),
  ),
  Team(
    teamId: 124,
    teamName: 'Carolina Hurricanes',
    arenaName: 'PNC Arena',
    arenaLocation: 'Raleigh, North Carolina',
    state: 'North Carolina',
    logoPath: 'lib/assets/leagues/nhl/hurricanes.svg',
    abbName: 'CAR',
    leagueId: 3,
    color: const Color(0xFFCC0000),
  ),
  Team(
    teamId: 125,
    teamName: 'Chicago Blackhawks',
    arenaName: 'United Center',
    arenaLocation: 'Chicago, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/nhl/blackhawks.svg',
    abbName: 'CHI',
    leagueId: 3,
    color: const Color(0xFFCE1126),
  ),
  Team(
    teamId: 126,
    teamName: 'Colorado Avalanche',
    arenaName: 'Ball Arena',
    arenaLocation: 'Denver, Colorado',
    state: 'Colorado',
    logoPath: 'lib/assets/leagues/nhl/avalanche.svg',
    abbName: 'COL',
    leagueId: 3,
    color: const Color(0xFF6F263D),
  ),
  Team(
    teamId: 127,
    teamName: 'Columbus Blue Jackets',
    arenaName: 'Nationwide Arena',
    arenaLocation: 'Columbus, Ohio',
    state: 'Ohio',
    logoPath: 'lib/assets/leagues/nhl/bluejackets.svg',
    abbName: 'CBJ',
    leagueId: 3,
    color: const Color(0xFF002654),
  ),
  Team(
    teamId: 128,
    teamName: 'Dallas Stars',
    arenaName: 'American Airlines Center',
    arenaLocation: 'Dallas, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nhl/stars.svg',
    abbName: 'DAL',
    leagueId: 3,
    color: const Color(0xFF006847),
  ),
  Team(
    teamId: 129,
    teamName: 'Detroit Red Wings',
    arenaName: 'Little Caesars Arena',
    arenaLocation: 'Detroit, Michigan',
    state: 'Michigan',
    logoPath: 'lib/assets/leagues/nhl/redwings.svg',
    abbName: 'DET',
    leagueId: 3,
    color: const Color(0xFFCE1126),
  ),
  Team(
    teamId: 130,
    teamName: 'Edmonton Oilers',
    arenaName: 'Rogers Place',
    arenaLocation: 'Edmonton, Alberta',
    state: 'Alberta',
    logoPath: 'lib/assets/leagues/nhl/oilers.svg',
    abbName: 'EDM',
    leagueId: 3,
    color: const Color(0xFF041E42),
  ),
  Team(
    teamId: 131,
    teamName: 'Florida Panthers',
    arenaName: 'BB&T Center',
    arenaLocation: 'Sunrise, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nhl/panthers.svg',
    abbName: 'FLA',
    leagueId: 3,
    color: const Color(0xFFC8102E),
  ),
  Team(
    teamId: 132,
    teamName: 'Los Angeles Kings',
    arenaName: 'Crypto.com Arena',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nhl/kings.svg',
    abbName: 'LAK',
    leagueId: 3,
    color: const Color(0xFF111111),
  ),
  Team(
    teamId: 133,
    teamName: 'Minnesota Wild',
    arenaName: 'Xcel Energy Center',
    arenaLocation: 'St. Paul, Minnesota',
    state: 'Minnesota',
    logoPath: 'lib/assets/leagues/nhl/wild.svg',
    abbName: 'MIN',
    leagueId: 3,
    color: const Color(0xFF154734),
  ),
  Team(
    teamId: 134,
    teamName: 'Montreal Canadiens',
    arenaName: 'Bell Centre',
    arenaLocation: 'Montreal, Quebec',
    state: 'Quebec',
    logoPath: 'lib/assets/leagues/nhl/canadiens.svg',
    abbName: 'MTL',
    leagueId: 3,
    color: const Color(0xFFAF1E2D),
  ),
  Team(
    teamId: 135,
    teamName: 'Nashville Predators',
    arenaName: 'Bridgestone Arena',
    arenaLocation: 'Nashville, Tennessee',
    state: 'Tennessee',
    logoPath: 'lib/assets/leagues/nhl/predators.svg',
    abbName: 'NSH',
    leagueId: 3,
    color: const Color(0xFFFDBB30),
  ),
  Team(
    teamId: 136,
    teamName: 'New Jersey Devils',
    arenaName: 'Prudential Center',
    arenaLocation: 'Newark, New Jersey',
    state: 'New Jersey',
    logoPath: 'lib/assets/leagues/nhl/devils.svg',
    abbName: 'NJD',
    leagueId: 3,
    color: const Color(0xFFCE1126),
  ),
  Team(
    teamId: 137,
    teamName: 'New York Islanders',
    arenaName: 'UBS Arena',
    arenaLocation: 'Elmont, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nhl/islanders.svg',
    abbName: 'NYI',
    leagueId: 3,
    color: const Color(0xFF00529B),
  ),
  Team(
    teamId: 138,
    teamName: 'New York Rangers',
    arenaName: 'Madison Square Garden',
    arenaLocation: 'New York, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/nhl/rangers.svg',
    abbName: 'NYR',
    leagueId: 3,
    color: const Color(0xFF0038A8),
  ),
  Team(
    teamId: 139,
    teamName: 'Ottawa Senators',
    arenaName: 'Canadian Tire Centre',
    arenaLocation: 'Ottawa, Ontario',
    state: 'Ontario',
    logoPath: 'lib/assets/leagues/nhl/senators.svg',
    abbName: 'OTT',
    leagueId: 3,
    color: const Color(0xFFE31837),
  ),
  Team(
    teamId: 140,
    teamName: 'Philadelphia Flyers',
    arenaName: 'Wells Fargo Center',
    arenaLocation: 'Philadelphia, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/nhl/flyers.svg',
    abbName: 'PHI',
    leagueId: 3,
    color: const Color(0xFFF74902),
  ),
  Team(
    teamId: 141,
    teamName: 'Pittsburgh Penguins',
    arenaName: 'PPG Paints Arena',
    arenaLocation: 'Pittsburgh, Pennsylvania',
    state: 'Pennsylvania',
    logoPath: 'lib/assets/leagues/nhl/penguins.svg',
    abbName: 'PIT',
    leagueId: 3,
    color: const Color(0xFFFCB514),
  ),
  Team(
    teamId: 142,
    teamName: 'San Jose Sharks',
    arenaName: 'SAP Center at San Jose',
    arenaLocation: 'San Jose, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nhl/sharks.svg',
    abbName: 'SJS',
    leagueId: 3,
    color: const Color(0xFF006272),
  ),
  Team(
    teamId: 143,
    teamName: 'Seattle Kraken',
    arenaName: 'Climate Pledge Arena',
    arenaLocation: 'Seattle, Washington',
    state: 'Washington',
    logoPath: 'lib/assets/leagues/nhl/kraken.svg',
    abbName: 'SEA',
    leagueId: 3,
    color: const Color(0xFF001628),
  ),
  Team(
    teamId: 144,
    teamName: 'St. Louis Blues',
    arenaName: 'Enterprise Center',
    arenaLocation: 'St. Louis, Missouri',
    state: 'Missouri',
    logoPath: 'lib/assets/leagues/nhl/blues.svg',
    abbName: 'STL',
    leagueId: 3,
    color: const Color(0xFF002F87),
  ),
  Team(
    teamId: 145,
    teamName: 'Tampa Bay Lightning',
    arenaName: 'Amalie Arena',
    arenaLocation: 'Tampa, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nhl/lightning.svg',
    abbName: 'TBL',
    leagueId: 3,
    color: const Color(0xFF002868),
  ),
  Team(
    teamId: 146,
    teamName: 'Toronto Maple Leafs',
    arenaName: 'Scotiabank Arena',
    arenaLocation: 'Toronto, Ontario',
    state: 'Ontario',
    logoPath: 'lib/assets/leagues/nhl/mapleleafs.svg',
    abbName: 'TOR',
    leagueId: 3,
    color: const Color(0xFF00205B),
  ),
  Team(
    teamId: 147,
    teamName: 'Vancouver Canucks',
    arenaName: 'Rogers Arena',
    arenaLocation: 'Vancouver, British Columbia',
    state: 'British Columbia',
    logoPath: 'lib/assets/leagues/nhl/canucks.svg',
    abbName: 'VAN',
    leagueId: 3,
    color: const Color(0xFF00205B),
  ),
  Team(
    teamId: 148,
    teamName: 'Vegas Golden Knights',
    arenaName: 'T-Mobile Arena',
    arenaLocation: 'Paradise, Nevada',
    state: 'Nevada',
    logoPath: 'lib/assets/leagues/nhl/goldenknights.svg',
    abbName: 'VGK',
    leagueId: 3,
    color: const Color(0xFFB4975A),
  ),
  Team(
    teamId: 149,
    teamName: 'Washington Capitals',
    arenaName: 'Capital One Arena',
    arenaLocation: 'Washington, D.C.',
    state: 'Washington, D.C.',
    logoPath: 'lib/assets/leagues/nhl/capitals.svg',
    abbName: 'WSH',
    leagueId: 3,
    color: const Color(0xFFC8102E),
  ),
  Team(
    teamId: 150,
    teamName: 'Winnipeg Jets',
    arenaName: 'Canada Life Centre',
    arenaLocation: 'Winnipeg, Manitoba',
    state: 'Manitoba',
    logoPath: 'lib/assets/leagues/nhl/jets.svg',
    abbName: 'WPG',
    leagueId: 3,
    color: const Color(0xFF041E42),
  ),
];
