import 'package:flutter/material.dart';
import 'package:tw_mobile/data/classes/team.dart';

List<Team> nwslTeams = [
  Team(
    teamId: 1,
    teamName: 'Angel City FC',
    arenaName: 'BMO Stadium',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nwsl/angelcity.svg',
    abbName: 'ACFC',
    leagueId: 7,
    color: const Color(0xFF80499B),
  ),
  Team(
    teamId: 2,
    teamName: 'Chicago Red Stars',
    arenaName: 'SeatGeek Stadium',
    arenaLocation: 'Bridgeview, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/nwsl/chicago.svg',
    abbName: 'CRS',
    leagueId: 7,
    color: const Color(0xFF700025),
  ),
  Team(
    teamId: 3,
    teamName: 'Houston Dash',
    arenaName: ' 	Shell Energy Stadium',
    arenaLocation: 'Houston, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/nwsl/houston.svg',
    abbName: 'HOU',
    leagueId: 7,
    color: const Color(0xFFF36D2B),
  ),
  Team(
    teamId: 4,
    teamName: 'Kansas City Current',
    arenaName: 'Children\'s Mercy Park',
    arenaLocation: 'Kansas City, Kansas',
    state: 'Kansas',
    logoPath: 'lib/assets/leagues/nwsl/kansascity.svg',
    abbName: 'KC',
    leagueId: 7,
    color: const Color(0xFF7A171A),
  ),
  Team(
    teamId: 5,
    teamName: 'NJ/NY Gotham FC',
    arenaName: 'Red Bull Arena',
    arenaLocation: 'Harrison, New Jersey',
    state: 'New Jersey',
    logoPath: 'lib/assets/leagues/nwsl/njnygotham.svg',
    abbName: 'GTH',
    leagueId: 7,
    color: const Color(0xFF0090D7),
  ),
  Team(
    teamId: 6,
    teamName: 'North Carolina Courage',
    arenaName: 'WakeMed Soccer Park',
    arenaLocation: 'Cary, North Carolina',
    state: 'North Carolina',
    logoPath: 'lib/assets/leagues/nwsl/northcarolina.svg',
    abbName: 'NC',
    leagueId: 7,
    color: const Color(0xFF0C2340),
  ),
  Team(
    teamId: 7,
    teamName: 'OL Reign',
    arenaName: 'Lumen Field',
    arenaLocation: 'Seattle, Washington',
    state: 'Washington',
    logoPath: 'lib/assets/leagues/nwsl/olreign.svg',
    abbName: 'OLR',
    leagueId: 7,
    color: const Color(0xFF12385C),
  ),
  Team(
    teamId: 8,
    teamName: 'Orlando Pride',
    arenaName: 'Exploria Stadium',
    arenaLocation: 'Orlando, Florida',
    state: 'Florida',
    logoPath: 'lib/assets/leagues/nwsl/orlando.svg',
    abbName: 'ORL',
    leagueId: 7,
    color: const Color(0xFF522398),
  ),
  Team(
    teamId: 9,
    teamName: 'Portland Thorns FC',
    arenaName: 'Providence Park',
    arenaLocation: 'Portland, Oregon',
    state: 'Oregon',
    logoPath: 'lib/assets/leagues/nwsl/portland.svg',
    abbName: 'POR',
    leagueId: 7,
    color: const Color(0xFFED1E79),
  ),
  Team(
    teamId: 10,
    teamName: 'Racing Louisville FC',
    arenaName: 'Lynn Family Stadium',
    arenaLocation: 'Louisville, Kentucky',
    state: 'Kentucky',
    logoPath: 'lib/assets/leagues/nwsl/louisville.svg',
    abbName: 'LOU',
    leagueId: 7,
    color: const Color(0xFF7A0019),
  ),
  Team(
    teamId: 11,
    teamName: 'San Diego Wave FC',
    arenaName: 'Snapdragon Stadium',
    arenaLocation: 'San Diego, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/nwsl/sandiegowave.svg',
    abbName: 'SDW',
    leagueId: 7,
    color: const Color(0xFF38A5DB),
  ),
  Team(
    teamId: 12,
    teamName: 'Washington Spirit',
    arenaName: 'Audi Field',
    arenaLocation: 'Washington, D.C.',
    state: 'Washington, D.C.',
    logoPath: 'lib/assets/leagues/nwsl/washington.svg',
    abbName: 'WAS',
    leagueId: 7,
    color: const Color(0xFFAB2328),
  ),
];
