import 'package:flutter/material.dart';
import 'package:tw_mobile/data/classes/team.dart';

List<Team> wnbaTeams = [
  Team(
    teamId: 1,
    teamName: 'Atlanta Dream',
    arenaName: 'Gateway Center Arena',
    arenaLocation: 'College Park, Georgia',
    state: 'Georgia',
    logoPath: 'lib/assets/leagues/wnba/atlanta.svg',
    abbName: 'ATL',
    leagueId: 6,
    color: const Color(0xFFE03A3E),
  ),
  Team(
    teamId: 2,
    teamName: 'Chicago Sky',
    arenaName: 'Wintrust Arena',
    arenaLocation: 'Chicago, Illinois',
    state: 'Illinois',
    logoPath: 'lib/assets/leagues/wnba/chicago.svg',
    abbName: 'CHI',
    leagueId: 6,
    color: const Color(0xFFC60033),
  ),
  Team(
    teamId: 3,
    teamName: 'Connecticut Sun',
    arenaName: 'Mohegan Sun Arena',
    arenaLocation: 'Uncasville, Connecticut',
    state: 'Connecticut',
    logoPath: 'lib/assets/leagues/wnba/connecticut.svg',
    abbName: 'CON',
    leagueId: 6,
    color: const Color(0xFFFFC72C),
  ),
  Team(
    teamId: 4,
    teamName: 'Dallas Wings',
    arenaName: 'College Park Center',
    arenaLocation: 'Arlington, Texas',
    state: 'Texas',
    logoPath: 'lib/assets/leagues/wnba/dallas.svg',
    abbName: 'DAL',
    leagueId: 6,
    color: const Color(0xFF0099C6),
  ),
  Team(
    teamId: 5,
    teamName: 'Indiana Fever',
    arenaName: 'Gainbridge Fieldhouse',
    arenaLocation: 'Indianapolis, Indiana',
    state: 'Indiana',
    logoPath: 'lib/assets/leagues/wnba/indiana.svg',
    abbName: 'IND',
    leagueId: 6,
    color: const Color(0xFFFFB44B),
  ),
  Team(
    teamId: 6,
    teamName: 'Las Vegas Aces',
    arenaName: 'Michelob Ultra Arena',
    arenaLocation: 'Las Vegas, Nevada',
    state: 'Nevada',
    logoPath: 'lib/assets/leagues/wnba/lasvegas.svg',
    abbName: 'LVA',
    leagueId: 6,
    color: const Color(0xFFA1A1A4),
  ),
  Team(
    teamId: 7,
    teamName: 'Los Angeles Sparks',
    arenaName: 'Crypto.com Arena',
    arenaLocation: 'Los Angeles, California',
    state: 'California',
    logoPath: 'lib/assets/leagues/wnba/losangeles.svg',
    abbName: 'LAS',
    leagueId: 6,
    color: const Color(0xFFFF1D11),
  ),
  Team(
    teamId: 8,
    teamName: 'Minnesota Lynx',
    arenaName: 'Target Center',
    arenaLocation: 'Minneapolis, Minnesota',
    state: 'Minnesota',
    logoPath: 'lib/assets/leagues/wnba/minnesota.svg',
    abbName: 'MIN',
    leagueId: 6,
    color: const Color(0xFF005083),
  ),
  Team(
    teamId: 9,
    teamName: 'New York Liberty',
    arenaName: 'Barclays Center',
    arenaLocation: 'Brooklyn, New York',
    state: 'New York',
    logoPath: 'lib/assets/leagues/wnba/newyork.svg',
    abbName: 'NYL',
    leagueId: 6,
    color: const Color(0xFFF3722C),
  ),
  Team(
    teamId: 10,
    teamName: 'Phoenix Mercury',
    arenaName: 'Footprint Center',
    arenaLocation: 'Phoenix, Arizona',
    state: 'Arizona',
    logoPath: 'lib/assets/leagues/wnba/phoenix.svg',
    abbName: 'PHX',
    leagueId: 6,
    color: const Color(0xFFE56020),
  ),
  Team(
    teamId: 11,
    teamName: 'Seattle Storm',
    arenaName: 'Climate Pledge Arena',
    arenaLocation: 'Seattle, Washington',
    state: 'Washington',
    logoPath: 'lib/assets/leagues/wnba/seattle.svg',
    abbName: 'SEA',
    leagueId: 6,
    color: const Color(0xFF0056B5),
  ),
  Team(
    teamId: 12,
    teamName: 'Washington Mystics',
    arenaName: 'Entertainment and Sports Arena',
    arenaLocation: 'Washington, D.C.',
    state: 'Washington, D.C.',
    logoPath: 'lib/assets/leagues/wnba/washington.svg',
    abbName: 'WAS',
    leagueId: 6,
    color: const Color(0xFFBD9BDC),
  ),
];
